# 1. Giới thiệu

* Thuật toán dựa trên định lý Bayes với các feature **độc lập với nhau**. Giả sử ta có 3 thông tin: tuổi, thâm niên, kinh nghiệm. Từ ba thông tin này để dự đoán ra loại nhân viên, lúc này ta sẽ xem xét xem liệu tuổi có ảnh hưởng đến loại ko, thâm niên có ảnh hưởng đến loại ko và kinh nghiệm có ảnh hưởng đến loại ko.
* Mô hình này rất tốt để train cho các tập dữ liệu lớn.
* Kết quả dự đoán cho ra rất tốt và dc sử dụng nhiều hơn các thuật toán khác vì tốc độ training model nhanh nhưng hiệu suất tổng quát kém hơn Logistic Regression hay LinearSVC.
* Có ba loại phân phối sử dụng phổ biến của Naive Bayes là GaussianNB, Bernoulli NB và MultinomialNB, tùy theo đặc điểm của dữ liệu mà ta sẽ phải áp dụng phân phối phù hợp cho model.
  * GaussianNB: mean = 0 và variance = 1, phân phối dạng hình chuông, đối xứng vs nhau qua mean, tại mean thì ba giá trị mean = median = mode. Áp dụng dc luôn cho bài toán liên tục hoặc phân loại. Sử dụng trên dữ liệu có nh chiều _(high-dimensional data)_.
  * BernoulliNB: áp dụng cho dữ liệu phân loại dạng nhị phận, sử dụng rộng rãi cho dữ liệu đếm thưa thớt _(Sparse Count Data)_ _(ví dụ là văn bản, xem lại `CountVectorizer`)_.
    Ví dụ ma trận thưa thớt trong văn bản:
    ![](../images/29.png)

  * MultinomialNB: áp dụng cho dữ liệu đếm _(nghĩa là mỗi đối tượng đại diện cho một số nguyên đếm của thứ gì đó, ví dụ tần suất một từ xuất hiện trong câu)_. Dc áp dụng rộng rãi cho Sparse Count Data.
* Naive Bayes thường dc ưu tiên sử dụng đối vs các bài toán cần phân loại văn bản.
* So sánh BernoulliNB và MultinomialNB:
  * Cả hai đều dc chủ yếu sử dụng trong phân loại dữ liệu văn bản.
  * MultiomialNB thường hoạt động tốt hơn so với BernoulliNB.

# 2. Ứng dụng
* Realtime Prediction _(dự đoán thời gian thực)_.
* Multiclass Prediction _(dự đoán đa lớp)_.
* Text Classification _(phân loại văn bản)_/ Spam Filtering _(lọc thư rác)_/ Sentiment Analysis _(phân tích trạng thái - trong phân tích truyền thông xã hội, để xác định tình cảm khách hàng - tích cực và tiêu cực)_.
* Recommendation System _(hệ thống đề xuất)_: Naive Bayes Classifier và Collabarative Filtering cùng nhau xậy dựng hệ thống đề xuất sử dụng kĩ thuật Machine Learning và khai thác dữ liệu để lọc thông tin ko xác định và dự đoán ng dùng có muốn một tài nguyên cụ thể hay ko.

# 3. Thuật toán
* Định lí Bayes cung cấpmột cách tính xác suất như sau:
  $$P(c|x) = \dfrac{P(x|c)*P(c)}{P(x)}$$
  $$P(c|X) = P(x_1|c)*P(x_2|c)*...*P(x_n|c)*P(c)$$
  Trong đó:
    * $P(c|x)$: xác suất xảy ra của một biến cố ngẫu nhiên - $c$ khi biết biến cố liên quan - $x$ xảy ra.
    * $P(x|c)$: xác suất xảy ra - $x$ khi biết $c$ xảy ra.
    * $P(c)$: xác suất xảy ra của riêng $c$ mà ko quan tâm tới $x$.
    * $P(x))$: xác suất xảy ra của riêng $x$ mà ko quan tâm tới $c$.
* Phân loại Naive Bayes giả định rằng tác động của giá trị của một yếu tố dự báo - predictor - $x$ trên một lớp nhất định - $c$ là độc lập vs các giá trị của các yếu tố dự báo khác. Giả định này dc gọi là lớp độc lập có điều kiện.

## 3.1. Ví dụ: Car Theft _(trộm cắp xe)_
* Xác định xe có bị ăn trộm hay ko.
* Các attribute: `Color` _(màu)_, `Type` _(loại xe)_, `Origin` _(nguồn gốc xuất xứ)_ và biến dự đoán `Stolen` _(có bị cắp hay ko)_.
* Dataset:<br>
  ![](../images/30.png)

# 4. Ưu điểm
* Tính toán nhanh chóng.
* Dễ triển khai.
* Hoạt động tốt vs bộ dữ liệu nhiều hoặc nhỏ, nhiều chiều.
* Hoạt động ngay cả khi phân phối ko chuẩn cho lắm.

# 5. Khuyết điểm
* Có thể có các biến đầu vào tương quan vs nhau (đa cộng tuyến), và khi 2 feature này dc chọn để build model thì có thể dẫn đến việc vượt quá tầm quan trọng.
* Nếu có một loại trong data train nhưng lại có trong test data thì nó sẽ ko dự doán dc, điều này thường dc gọi là tần số ko $\Rightarrow$ để giải quyết có thể sử dụng kĩ thuật làm mịn, một kĩ thuật phổ biến là Laplace.
* Có thể có feature liên tục mà ko có phân phối chuẩn, thì trong tình huống này ta nên biến đổi nó bằng các phương pháp khác nhau hoặc biến biến liên tục thành biến phân loại.

# 6. Các bước thực hiện
* Chọn model áp dụng là Naive Bayes
* Áp dụng model phù hợp là GaussianNB, BernoulliNB hay MultinomialNB
* Tách dữ liệu thành traing data và test data.
* Huấn luyện model với training data.
* Sử dụng model để dự đoán test data hoặc vs dữ liệu mới.
* Đánh giá độ chính xác.

# 7. Demo vs python

Đọc dữ liệu

In [5]:
import numpy as np
import pandas as pd
from modules.preprocessing import CPreprocessing

ModuleNotFoundError: No module named 'pandas_profiling'

In [4]:
X = pd.DataFrame(X, columns=['color', 'type', 'origin'])
X_now = pd.get_dummies(X)

X_now

color_Red  color_Yellow  type_SUV  type_Sports  origin_Domestic  \
0          1             0         0            1                1   
1          1             0         0            1                1   
2          1             0         0            1                1   
3          0             1         0            1                1   
4          0             1         0            1                0   
5          0             1         1            0                0   
6          0             1         1            0                0   
7          0             1         1            0                1   
8          1             0         1            0                0   
9          1             0         0            1                0   

   origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [1]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([["Red", "Sports", "Domestic"],
              ["Red", "Sports", "Domestic"], 
              ["Red", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Imported"],
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Domestic"],
              ["Red", "SUV", "Imported"], 
              ["Red", "Sports", "Imported"]])
Y = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "Yes"])

In [3]:
X = pd.DataFrame(X, columns=['color', 'type', 'origin'])
X_now = pd.get_dummies(X)
X_now

color_Red  color_Yellow  type_SUV  type_Sports  origin_Domestic  \
0          1             0         0            1                1   
1          1             0         0            1                1   
2          1             0         0            1                1   
3          0             1         0            1                1   
4          0             1         0            1                0   
5          0             1         1            0                0   
6          0             1         1            0                0   
7          0             1         1            0                1   
8          1             0         1            0                0   
9          1             0         0            1                0   

   origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [4]:
Y = pd.DataFrame(Y, columns=['stolen'])
Y_now = pd.get_dummies(Y, drop_first=True)

Y_now

stolen_Yes
0           1
1           0
2           1
3           0
4           1
5           0
6           1
7           0
8           0
9           1

In [5]:
from sklearn.naive_bayes import BernoulliNB


clf = BernoulliNB()
clf.fit(X_now, Y_now)

/home/manhcuong/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BernoulliNB()

In [6]:
X_new = [[1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1]] # red, suv, domestic; yellow, sport, imported

In [7]:
predicted = clf.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [8]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [9]:
model.fit(X_now, Y_now)

/home/manhcuong/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [10]:
predicted = model.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [11]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
text_data = np.array([
    'I love Vietnam. Vietnam!',
    'Vietnam is best',
    'Hochiminh City is the bigest city of Vietnam'
])

In [16]:
y = np.array([0, 0, 1])

In [13]:
count = CountVectorizer()
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [14]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, 0, 0, 1, 0, 0, 2],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 2, 1, 1, 0, 1, 1, 1]])

In [17]:
clf = MultinomialNB()
model = clf.fit(X, y)

In [18]:
import numpy as np

print('The prediction accuracy is', model.score(X, y)*100, '%')


The prediction accuracy is 100.0 %


In [20]:
test_data = np.array([
    'Vietnam is beautiful country',
    'I live in Hochiminh City'
])

X_test = count.transform(test_data)
X_test = X_test.toarray()
X_test

array([[0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0]])

In [21]:
y_pred = model.predict(X_test)
y_pred

array([0, 1])

# Save model to file

In [22]:
import pickle

pkl_filename = 'model_city_class.pkl'
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

In [23]:
import pickle
pkl_filename = 'model_city_class.pkl'

with open(pkl_filename, 'rb') as file:
    saved_model = pickle.load(file)