# 1. Giới thiệu
* Thuật toán dựa trên định lý Bayes với các feature **độc lập với nhau**. Giả sử ta có 3 thông tin: tuổi, thâm niên, kinh nghiệm. Từ ba thông tin này để dự đoán ra loại nhân viên, lúc này ta sẽ xem xét xem liệu tuổi có ảnh hưởng đến loại ko, thâm niên có ảnh hưởng đến loại ko và kinh nghiệm có ảnh hưởng đến loại ko.
* Mô hình này rất tốt để train cho các tập dữ liệu lớn.
* Kết quả dự đoán cho ra rất tốt và dc sử dụng nhiều hơn các thuật toán khác vì tốc độ training model nhanh nhưng hiệu suất tổng quát kém hơn Logistic Regression hay LinearSVC.
* Có ba loại phân phối sử dụng phổ biến của Naive Bayes là GaussianNB, Bernoulli NB và MultinomialNB, tùy theo đặc điểm của dữ liệu mà ta sẽ phải áp dụng phân phối phù hợp cho model.
  * GaussianNB: mean = 0 và variance = 1, phân phối dạng hình chuông, đối xứng vs nhau qua mean, tại mean thì ba giá trị mean = median = mode. Áp dụng dc luôn cho bài toán liên tục hoặc phân loại. Sử dụng trên dữ liệu có nh chiều _(high-dimensional data)_.
  * BernoulliNB: áp dụng cho dữ liệu phân loại dạng nhị phận, sử dụng rộng rãi cho dữ liệu đếm thưa thớt _(Sparse Count Data)_ _(ví dụ là văn bản, xem lại `CountVectorizer`)_.
    Ví dụ ma trận thưa thớt trong văn bản:
    ![](../images/29.png)

  * MultinomialNB: áp dụng cho dữ liệu đếm _(nghĩa là mỗi đối tượng đại diện cho một số nguyên đếm của thứ gì đó, ví dụ tần suất một từ xuất hiện trong câu)_. Dc áp dụng rộng rãi cho Sparse Count Data.
* Naive Bayes thường dc ưu tiên sử dụng đối vs các bài toán cần phân loại văn bản.
* So sánh BernoulliNB và MultinomialNB:
  * Cả hai đều dc chủ yếu sử dụng trong phân loại dữ liệu văn bản.
  * MultiomialNB thường hoạt động tốt hơn so với BernoulliNB.

# 2. Ứng dụng
* Realtime Prediction _(dự đoán thời gian thực)_.
* Multiclass Prediction _(dự đoán đa lớp)_.
* Text Classification _(phân loại văn bản)_/ Spam Filtering _(lọc thư rác)_/ Sentiment Analysis _(phân tích trạng thái - trong phân tích truyền thông xã hội, để xác định tình cảm khách hàng - tích cực và tiêu cực)_.
* Recommendation System _(hệ thống đề xuất)_: Naive Bayes Classifier và Collabarative Filtering cùng nhau xậy dựng hệ thống đề xuất sử dụng kĩ thuật Machine Learning và khai thác dữ liệu để lọc thông tin ko xác định và dự đoán ng dùng có muốn một tài nguyên cụ thể hay ko.

# 3. Thuật toán
* Định lí Bayes cung cấpmột cách tính xác suất như sau:
  $$P(c|x) = \dfrac{P(x|c)*P(c)}{P(x)}$$
  $$P(c|X) = P(x_1|c)*P(x_2|c)*...*P(x_n|c)*P(c)$$
  Trong đó:
    * $P(c|x)$: xác suất xảy ra của một biến cố ngẫu nhiên - $c$ khi biết biến cố liên quan - $x$ xảy ra.
    * $P(x|c)$: xác suất xảy ra - $x$ khi biết $c$ xảy ra.
    * $P(c)$: xác suất xảy ra của riêng $c$ mà ko quan tâm tới $x$.
    * $P(x))$: xác suất xảy ra của riêng $x$ mà ko quan tâm tới $c$.
* Phân loại Naive Bayes giả định rằng tác động của giá trị của một yếu tố dự báo - predictor - $x$ trên một lớp nhất định - $c$ là độc lập vs các giá trị của các yếu tố dự báo khác. Giả định này dc gọi là lớp độc lập có điều kiện.

## 3.1. Ví dụ: Car Theft _(trộm cắp xe)_
* Xác định xe có bị ăn trộm hay ko.
* Các attribute: `Color` _(màu)_, `Type` _(loại xe)_, `Origin` _(nguồn gốc xuất xứ)_ và biến dự đoán `Stolen` _(có bị cắp hay ko)_.
* Dataset:<br>
  ![](../images/30.png)

# 4. Ưu điểm
* Tính toán nhanh chóng.
* Dễ triển khai.
* Hoạt động tốt vs bộ dữ liệu nhiều hoặc nhỏ, nhiều chiều.
* Hoạt động ngay cả khi phân phối ko chuẩn cho lắm.

# 5. Khuyết điểm
* Có thể có các biến đầu vào tương quan vs nhau (đa cộng tuyến), và khi 2 feature này dc chọn để build model thì có thể dẫn đến việc vượt quá tầm quan trọng.
* Nếu có một loại trong data train nhưng lại có trong test data thì nó sẽ ko dự doán dc, điều này thường dc gọi là tần số ko $\Rightarrow$ để giải quyết có thể sử dụng kĩ thuật làm mịn, một kĩ thuật phổ biến là Laplace.
* Có thể có feature liên tục mà ko có phân phối chuẩn, thì trong tình huống này ta nên biến đổi nó bằng các phương pháp khác nhau hoặc biến biến liên tục thành biến phân loại.

# 6. Các bước thực hiện
* Chọn model áp dụng là Naive Bayes
* Áp dụng model phù hợp là GaussianNB, BernoulliNB hay MultinomialNB
* Tách dữ liệu thành traing data và test data.
* Huấn luyện model với training data.
* Sử dụng model để dự đoán test data hoặc vs dữ liệu mới.
* Đánh giá độ chính xác.

# 7. Demo vs python

In [1]:
import numpy as np
import pandas as pd
from modules.preprocessing import CPreprocessing

Đọc dữ liệu và chuẩn bị dữ liệu

In [2]:
X = np.array([
    ['Red', 'Sports', 'Domestic'],
    ['Red', 'Sports', 'Domestic'],
    ['Red', 'Sports', 'Domestic'],
    ['Yellow', 'Sports', 'Domestic'],
    ['Yellow', 'Sports', 'Imported'],
    ['Yellow', 'SUV', 'Imported'],
    ['Yellow', 'SUV', 'Imported'],
    ['Yellow', 'SUV', 'Domestic'],
    ['Red', 'SUV', 'Imported'],
    ['Red', 'Sports', 'Imported'],
])

y = np.array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes'])

In [3]:
X = pd.DataFrame(X, columns=['color', 'type', 'origin'])
X_now = CPreprocessing(X).encoding('dummy')

X_now

color_Red  color_Yellow  type_SUV  type_Sports  origin_Domestic  \
0          1             0         0            1                1   
1          1             0         0            1                1   
2          1             0         0            1                1   
3          0             1         0            1                1   
4          0             1         0            1                0   
5          0             1         1            0                0   
6          0             1         1            0                0   
7          0             1         1            0                1   
8          1             0         1            0                0   
9          1             0         0            1                0   

   origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [4]:
y = pd.DataFrame(y, columns=['stolen'])
y_now = CPreprocessing(y).encoding('dummy', drop_first=True)

y_now

stolen_Yes
0           1
1           0
2           1
3           0
4           1
5           0
6           1
7           0
8           0
9           1

Train model vs `BernoulliNB`

In [5]:
from modules.naive_bayes import CNaiveBayes

In [6]:
model = CNaiveBayes(X_now, y_now)
model.initModel('bernoulli')

/home/manhcuong/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Tiến hành dự đoán vs data mẫu

In [7]:
X_new = [[1, 0, 1, 0, 1, 0]] # red, suv, domestic

In [8]:
predicted = model.predict(X_new)

predicted

array([0], dtype=uint8)

> **Nhận xét**
> * Vs tập dữ liệu `red, suv, domestic` thì chiếc xe này sẽ ko bị ăn trộm

Train model với `GaussianNB`

In [9]:
model = CNaiveBayes(X_now, y_now)
model.initModel('gaussian')

/home/manhcuong/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [10]:
X_new = [[1, 0, 1, 0, 1, 0]] # red, suv, domestic

predicted = model.predict(X_new)

predicted

> **Nhận xét**
> * Vậy với Gaussian thì xe cũng sẽ ko bị ăn cắp.

Ví dụ cho MultinomialNB

In [11]:
from modules.text_transform import CTextHandler

In [12]:
text_data = np.array([
    'I love Vietnam. Vietnam!',
    'Vietnam is best',
    'Hochiminh is the biggest city of Vietnam'
])

In [13]:
y = np.array([0, 0, 1])

In [14]:
text_handler = CTextHandler(text_data)

In [15]:
X = text_handler.createBagOfWords()

In [16]:
X

array([[0, 0, 0, 0, 0, 1, 0, 0, 2],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 1]])

In [17]:
y

array([0, 0, 1])

Huấn luyện model

In [18]:
model = CNaiveBayes(X, y)
model.initModel('multinomial')

Kiểm tra độ chính xác của model

In [19]:
model.model.score(X, y)*100.0

100.0

> **Nhận xét**
> * Có 3 mẫu thôi nên 100% là đúng r ^^

Dự đoán vs model

In [20]:
test_data = np.array([
    'Vietnam is beautiful country',
    'I live in Hochiminh City'
])

X_test = text_handler.transform(test_data)

In [21]:
X_test

array([[0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0]])

In [22]:
y_pred = model.predict(X_test)

y_pred

array([0, 1])

> **Nhận xét**
> * Mẫu đầu thiên thuộc class 0 và mẫu thứ hai thuộc class 1

Lưu model và file bag_of_word bằng `pickle`

In [23]:
from modules.file import CPickleFile

Lưu model

In [24]:
CPickleFile().write(r'./from_class/model.pkl', model)

Success!


Lưu file bag of words

In [25]:
CPickleFile().write(r'./from_class/bag_of_words.pkl', text_handler)

Success!


Load model và bag of words từ `pickle` file

In [26]:
model_load = CPickleFile().read(r'./from_class/model.pkl')
text_handler_load = CPickleFile().read(r'./from_class/bag_of_words.pkl')

Success!
Success!


Test thử coi sài dc ko

In [27]:
test_new = np.array([
    'Welcome to Vietnam',
    'Welcome to Hochiminh City'
])

X_test_new = text_handler_load.transform(test_new)

X_test_new

array([[0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0]])

In [28]:
model.predict(X_test_new)

array([0, 1])

> **Nhận xét**
> * OKLA, chạy ổn