In [1]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([["Red", "Sports", "Domestic"],
              ["Red", "Sports", "Domestic"], 
              ["Red", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Imported"],
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Domestic"],
              ["Red", "SUV", "Imported"], 
              ["Red", "Sports", "Imported"]])
Y = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "Yes"])

In [3]:
X = pd.DataFrame(X, columns=['color', 'type', 'origin'])
X_now = pd.get_dummies(X)
X_now

color_Red  color_Yellow  type_SUV  type_Sports  origin_Domestic  \
0          1             0         0            1                1   
1          1             0         0            1                1   
2          1             0         0            1                1   
3          0             1         0            1                1   
4          0             1         0            1                0   
5          0             1         1            0                0   
6          0             1         1            0                0   
7          0             1         1            0                1   
8          1             0         1            0                0   
9          1             0         0            1                0   

   origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [4]:
Y = pd.DataFrame(Y, columns=['stolen'])
Y_now = pd.get_dummies(Y, drop_first=True)

Y_now

stolen_Yes
0           1
1           0
2           1
3           0
4           1
5           0
6           1
7           0
8           0
9           1

In [5]:
from sklearn.naive_bayes import BernoulliNB


clf = BernoulliNB()
clf.fit(X_now, Y_now)

/home/manhcuong/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BernoulliNB()

In [6]:
X_new = [[1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1]] # red, suv, domestic; yellow, sport, imported

In [7]:
predicted = clf.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [8]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [9]:
model.fit(X_now, Y_now)

/home/manhcuong/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [10]:
predicted = model.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [11]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
text_data = np.array([
    'I love Vietnam. Vietnam!',
    'Vietnam is best',
    'Hochiminh City is the bigest city of Vietnam'
])

In [16]:
y = np.array([0, 0, 1])

In [13]:
count = CountVectorizer()
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [14]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, 0, 0, 1, 0, 0, 2],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 2, 1, 1, 0, 1, 1, 1]])

In [17]:
clf = MultinomialNB()
model = clf.fit(X, y)

In [18]:
import numpy as np

print('The prediction accuracy is', model.score(X, y)*100, '%')


The prediction accuracy is 100.0 %


In [20]:
test_data = np.array([
    'Vietnam is beautiful country',
    'I live in Hochiminh City'
])

X_test = count.transform(test_data)
X_test = X_test.toarray()
X_test

array([[0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0]])

In [21]:
y_pred = model.predict(X_test)
y_pred

array([0, 1])

# Save model to file

In [22]:
import pickle

pkl_filename = 'model_city_class.pkl'
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

In [23]:
import pickle
pkl_filename = 'model_city_class.pkl'

with open(pkl_filename, 'rb') as file:
    saved_model = pickle.load(file)